<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x64</PlatformTarget>
		<LangVersion>preview</LangVersion>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Platforms>x64</Platforms>
		<OutputPath>..\..\bin\VMAT-TXI-CSI</OutputPath>
		<BaseOutputPath>..\..\bin\</BaseOutputPath>
		<Build>$([System.DateTime]::op_Subtraction($([System.DateTime]::get_Now().get_Date()),$([System.DateTime]::new(2000,1,1))).get_TotalDays())</Build>
		<Revision>$([MSBuild]::Divide($([System.DateTime]::get_Now().get_TimeOfDay().get_TotalMinutes()), 2).ToString('F0'))</Revision>
		<Version>1.0.$(Build).$(Revision)</Version>
		<Configurations>Release;Debug;Debug-v15;Debug-v16</Configurations>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<Reference Include="VMS.TPS.Common.Model.API">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.API.dll</HintPath>
		</Reference>
		<Reference Include="VMS.TPS.Common.Model.Types">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.Types.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'Debug-v16'">
		<Reference Include="VMS.TPS.Common.Model.API">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.API.dll</HintPath>
		</Reference>
		<Reference Include="VMS.TPS.Common.Model.Types">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.Types.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'Debug-v15'">
		<Reference Include="VMS.TPS.Common.Model.API">
			<HintPath>..\..\..\VMS_TPS_resources\15.6\VMS.TPS.Common.Model.API.dll</HintPath>
		</Reference>
		<Reference Include="VMS.TPS.Common.Model.Types">
			<HintPath>..\..\..\VMS_TPS_resources\15.6\VMS.TPS.Common.Model.Types.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
	  <PackageReference Include="Prism.Core" Version="9.0.537" />
	  <PackageReference Include="SimpleProgressWindow" Version="1.2.8594.18064" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="System.Windows.Forms" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Context\" />
	</ItemGroup>
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
	  <Exec Command="if NOT EXIST &quot;$(ProjectDir)$(OutDir)\configuration\&quot; (&#xD;&#xA;mkdir &quot;$(ProjectDir)$(OutDir)\configuration\&quot;&#xD;&#xA;)&#xD;&#xA;if NOT EXIST &quot;$(ProjectDir)$(OutDir)\logs\&quot; (&#xD;&#xA;mkdir &quot;$(ProjectDir)$(OutDir)\logs\&quot;&#xD;&#xA;)&#xD;&#xA;if NOT EXIST &quot;$(ProjectDir)$(OutDir)\documentation\&quot; (&#xD;&#xA;mkdir &quot;$(ProjectDir)$(OutDir)\documentation\&quot;&#xD;&#xA;)" />
	</Target>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="copy &quot;$(SolutionDir)Documentation\*&quot; &quot;$(ProjectDir)$(OutDir)\documentation&quot;" />
	</Target>

</Project>
