<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net472</TargetFramework>
	  <ImplicitUsings>disable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <UseWPF>true</UseWPF>
	  <PlatformTarget>x64</PlatformTarget>
	  <LangVersion>preview</LangVersion>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <Platforms>x64</Platforms>
	  <OutputPath>..\..\bin\VMAT-TXI-CSI</OutputPath>
	  <BaseOutputPath>..\..\bin\</BaseOutputPath>
	  <Build>$([System.DateTime]::op_Subtraction($([System.DateTime]::get_Now().get_Date()),$([System.DateTime]::new(2000,1,1))).get_TotalDays())</Build>
	  <Revision>$([MSBuild]::Divide($([System.DateTime]::get_Now().get_TimeOfDay().get_TotalMinutes()), 2).ToString('F0'))</Revision>
	  <Version>1.0.$(Build).$(Revision)</Version>
	  <Configurations>Release;Debug;Debug-v15;Debug-v16</Configurations>
  </PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<Reference Include="VMS.TPS.Common.Model.API">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.API.dll</HintPath>
		</Reference>
		<Reference Include="VMS.TPS.Common.Model.Types">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.Types.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'Debug-v16'">
		<Reference Include="VMS.TPS.Common.Model.API">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.API.dll</HintPath>
		</Reference>
		<Reference Include="VMS.TPS.Common.Model.Types">
			<HintPath>..\..\..\VMS_TPS_resources\16.1\VMS.TPS.Common.Model.Types.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'Debug-v15'">
		<Reference Include="VMS.TPS.Common.Model.API">
			<HintPath>..\..\..\VMS_TPS_resources\15.6\VMS.TPS.Common.Model.API.dll</HintPath>
		</Reference>
		<Reference Include="VMS.TPS.Common.Model.Types">
			<HintPath>..\..\..\VMS_TPS_resources\15.6\VMS.TPS.Common.Model.Types.dll</HintPath>
		</Reference>
	</ItemGroup>

  <ItemGroup>
    <Compile Remove="ImageClasses\**" />
    <EmbeddedResource Remove="ImageClasses\**" />
    <None Remove="ImageClasses\**" />
    <Page Remove="ImageClasses\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="SimpleITKCSharpNative.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SimpleITKCSharpNative.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EvilDICOM" Version="2.0.6.5" />
	  <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="SimpleITK-win64-CSharp-x64" Version="1.0.0.1" />
    <PackageReference Include="SimpleProgressWindow" Version="1.2.8594.18064" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoPlannerHelpers\AutoPlannerHelpers.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
